out_str <- c("<!DOCTYPE html>", "", "<html xmlns=\"http://www.w3.org/1999/xhtml\">",
             "", "<head>", "", "<meta charset=\"utf-8\">", "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />",
             "<meta name=\"generator\" content=\"pandoc\" />", "", "", "",
             "<title>Document</title>", "", "", "", "", "<link rel=\"stylesheet\" href=\"docx.css\" type=\"text/css\" />",
             "", "</head>", "", "<body>", "", "", "", "<div id=\"header\">",
             "<h1 class=\"title\" style=\"margin: 24pt 0pt 0pt 0pt;\">Document</h1>",
             "</div>", "", "", "<div id=\"header-1\" class=\"section level1\">",
             "<h1 style=\"margin: 24pt 0pt 0pt 0pt;\">Header 1</h1>", "<p>Test with header 1</p>",
             "<p>Second paragraph</p>", "<div id=\"header-2\" class=\"section level2\">",
             "<h2 style=\"margin: 24pt 0pt 0pt 0pt;\">Header 2</h2>", "<p>Test with header 2</p>",
             "<p>Second paragraph</p>", "<div id=\"header-3\" class=\"section level3\">",
             "<h3 style=\"margin: 24pt 0pt 0pt 0pt;\">Header 3</h3>", "<p>Test with header 3</p>",
             "<p>Second paragraph</p>", "<div id=\"header-4\" class=\"section level4\">",
             "<h4 style=\"margin: 24pt 0pt 0pt 0pt;\">Header 4</h4>", "<p>Test with header 4</p>",
             "<p>Second paragraph</p>", "<div id=\"header-5\" class=\"section level5\">",
             "<h5 style=\"margin: 24pt 0pt 0pt 0pt;\">Header 5</h5>", "<p>Test with header 5</p>",
             "<p>Second paragraph</p>", "<div id=\"header-6\" class=\"section level6\">",
             "<h6 style=\"margin: 24pt 0pt 0pt 0pt;\">Header 6</h6>", "<p>Test with header 6</p>",
             "<p>Second paragraph</p>", "</div>", "</div>", "</div>", "</div>",
             "</div>", "</div>", "<div id=\"tables\" class=\"section level1\">",
             "<h1 style=\"margin: 24pt 0pt 0pt 0pt;\">Tables</h1>", "<pre><code>## Loading required package: Hmisc",
             "## Loading required package: grid", "## Loading required package: lattice",
             "## Loading required package: survival", "## Loading required package: splines",
             "## Loading required package: Formula", "## ", "## Attaching package: &#39;Hmisc&#39;",
             "## ", "## The following objects are masked from &#39;package:base&#39;:",
             "## ", "##     format.pval, round.POSIXt, trunc.POSIXt, units</code></pre>",
             "<table class='gmisc_table' style='border-collapse: collapse;' >",
             "    <thead>", "    <tr><td colspan='6' style='text-align: left;'>",
             "    ", "Table 1: Patient demographics", "</td></tr>", "    <tr>",
             "        <th style='border-top: 2px solid grey;'></th>", "        <th colspan='1' style='font-weight: 900; border-top: 2px solid grey; text-align: center;'></th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>",
             " ", "</th>", "        <th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;'>",
             "Type of treatment<sup>†</sup>", "</th>", "    </tr>", "    <tr>",
             "        <th style='border-bottom: 1px solid grey; '> </th>",
             "        <th style='border-bottom: 1px solid grey; text-align: center;'>",
             "Total<br><font weight = normal; size = 1>n = 100</font>", "</th>",
             "        <th style='border-bottom: 1px solid grey;' colspan='1'>",
             " ", "</th>", "        <th style='border-bottom: 1px solid grey; text-align: center;'>",
             "Treated A<br><font weight = normal; size = 1>n = 27</font>",
             "</th>", "        <th style='border-bottom: 1px solid grey; text-align: center;'>",
             "Treatment B‡<br><font weight = normal; size = 1>n = 40</font>",
             "</th>", "        <th style='border-bottom: 1px solid grey; text-align: center;'>",
             "Placebo<br><font weight = normal; size = 1>n = 33</font>", "</th>",
             "    </tr>", "    </thead><tbody>", "    <tr><td colspan='6' style='font-weight: 900; text-transform:capitalize; text-align: center;'>",
             "Base", "</td></tr>", "    <tr style='background-color:#ffffff;'><td colspan='6' style='font-weight: 900;'>",
             "Age", "</td></tr>", "    <tr style='background-color:#ffffff;'>",
             "        <td style='text-align: left;'>", "  Median (IQR)", "</td>",
             "        <td style='text-align: right;'>", "52 ( 46 - 55)", "</td>",
             "        <td style='' colspan='1'>", " ", "</td>", "        <td style='text-align: center;'>",
             "52 ( 46 - 55)", "</td>", "        <td style='text-align: center;'>",
             "50 ( 46 - 54)", "</td>", "        <td style='text-align: center;'>",
             "52 ( 47 - 56)", "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'><td colspan='6' style='font-weight: 900; '>",
             "Some categorical<br>  variable", "</td></tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  A", "</td>", "        <td style='text-align: right;'>",
             "27 (27%)", "</td>", "        <td style='' colspan='1'>", " ",
             "</td>", "        <td style='text-align: center;'>", "6 (22%)",
             "</td>", "        <td style='text-align: center;'>", "15 (38%)",
             "</td>", "        <td style='text-align: center;'>", "6 (18%)",
             "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  B", "</td>", "        <td style='text-align: right;'>",
             "22 (22%)", "</td>", "        <td style='' colspan='1'>", " ",
             "</td>", "        <td style='text-align: center;'>", "9 (33%)",
             "</td>", "        <td style='text-align: center;'>", "7 (18%)",
             "</td>", "        <td style='text-align: center;'>", "6 (18%)",
             "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  C", "</td>", "        <td style='text-align: right;'>",
             "20 (20%)", "</td>", "        <td style='' colspan='1'>", " ",
             "</td>", "        <td style='text-align: center;'>", "7 (26%)",
             "</td>", "        <td style='text-align: center;'>", "6 (15%)",
             "</td>", "        <td style='text-align: center;'>", "7 (21%)",
             "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  D", "</td>", "        <td style='text-align: right;'>",
             "14 (14%)", "</td>", "        <td style='' colspan='1'>", " ",
             "</td>", "        <td style='text-align: center;'>", "2 (7%)",
             "</td>", "        <td style='text-align: center;'>", "4 (10%)",
             "</td>", "        <td style='text-align: center;'>", "8 (24%)",
             "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  E", "</td>", "        <td style='text-align: right;'>",
             "17 (17%)", "</td>", "        <td style='' colspan='1'>", " ",
             "</td>", "        <td style='text-align: center;'>", "3 (11%)",
             "</td>", "        <td style='text-align: center;'>", "8 (20%)",
             "</td>", "        <td style='text-align: center;'>", "6 (18%)",
             "</td>", "    </tr>", "    <tr><td colspan='6' style='font-weight: 900; text-transform:capitalize; text-align: center; border-top: 1px solid grey;'>",
             "Other", "</td></tr>", "    <tr style='background-color:#ffffff;'><td colspan='6' style='font-weight: 900; '>",
             "Sex", "</td></tr>", "    <tr style='background-color:#ffffff;'>",
             "        <td style='text-align: left;'>", "  Female", "</td>",
             "        <td style='text-align: right;'>", "49 (49%)", "</td>",
             "        <td style='' colspan='1'>", " ", "</td>", "        <td style='text-align: center;'>",
             "14 (52%)", "</td>", "        <td style='text-align: center;'>",
             "18 (45%)", "</td>", "        <td style='text-align: center;'>",
             "17 (52%)", "</td>", "    </tr>", "    <tr style='background-color:#ffffff;'>",
             "        <td style='text-align: left;'>", "  Male", "</td>",
             "        <td style='text-align: right;'>", "51 (51%)", "</td>",
             "        <td style='' colspan='1'>", " ", "</td>", "        <td style='text-align: center;'>",
             "13 (48%)", "</td>", "        <td style='text-align: center;'>",
             "22 (55%)", "</td>", "        <td style='text-align: center;'>",
             "16 (48%)", "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'><td colspan='6' style='font-weight: 900; '>",
             "Race", "</td></tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  Asian", "</td>",
             "        <td style='text-align: right;'>", "31 (31%)", "</td>",
             "        <td style='' colspan='1'>", " ", "</td>", "        <td style='text-align: center;'>",
             "7 (26%)", "</td>", "        <td style='text-align: center;'>",
             "11 (28%)", "</td>", "        <td style='text-align: center;'>",
             "13 (39%)", "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='text-align: left;'>", "  Black", "</td>",
             "        <td style='text-align: right;'>", "30 (30%)", "</td>",
             "        <td style='' colspan='1'>", " ", "</td>", "        <td style='text-align: center;'>",
             "4 (15%)", "</td>", "        <td style='text-align: center;'>",
             "15 (38%)", "</td>", "        <td style='text-align: center;'>",
             "11 (33%)", "</td>", "    </tr>", "    <tr style='background-color:#bfefff;'>",
             "        <td style='border-bottom: 2px solid grey; text-align: left;'>",
             "  White", "</td>", "        <td style='border-bottom: 2px solid grey; text-align: right;'>",
             "39 (39%)", "</td>", "        <td style='border-bottom: 2px solid grey;' colspan='1'>",
             " ", "</td>", "        <td style='border-bottom: 2px solid grey; text-align: center;'>",
             "16 (59%)", "</td>", "        <td style='border-bottom: 2px solid grey; text-align: center;'>",
             "14 (35%)", "</td>", "        <td style='border-bottom: 2px solid grey; text-align: center;'>",
             "9 (27%)", "</td>", "    </tr>", "    </tbody>", "    <tfoot><tr><td colspan=6>",
             "    ", "<font size=1>Abbreviations: ECOG, Eastern Cooperative Oncology Group;“,” PS, performance score</font><br><font size=1><sup>†</sup>Note 1. Trial groups for a new wonder drug</font><br><font size = 1><sup>‡</sup>Note 2. Twice the dosage of treatment A</font>",
             "</td></tr></tfoot>", "</table>", "", "</div>",

             "<div id=\"graph-tests\" class=\"section level1\">",
             "<h1 style=\"margin: 24pt 0pt 0pt 0pt;\">Graph tests</h1>",

             "<p>Basic plot:</p>",
             "<pre class=\"r\"><code>plot(cars)</code></pre>",
             "<div class=\"figure\">",
              "<img src=\"Full_test_suite_files/figure-html/Basic_graph.png\" alt=\"plot of chunk Basic_graph\" /><p class=\"caption\">plot of chunk Basic_graph</p>",
             "</div>",

             "<p>Height, width, and caption:</p>", "<pre class=\"r\"><code>plot(cars)</code></pre>",
             "<div class=\"figure\">",
              "<img src=\"Full_test_suite_files/figure-html/Height_width_caption.png\" alt=\"Test: Height, width, and caption\" /><p class=\"caption\">Test: Height, width, and caption</p>",
             "</div>",

             "<p>Height, width, caption, and dpi:</p>",
             "<pre class=\"r\"><code>plot(cars)</code></pre>",
             "<div class=\"figure\">",
              "<img src=\"Full_test_suite_files/figure-html/Height_width_caption_dpi.png\" alt=\"Test: Height, width, caption, and dpi\" /><p class=\"caption\">Test: Height, width, caption, and dpi</p>",
             "</div>",

             "<p>Height, width, caption, dpi, out.height, out.width:</p>",
             "<pre class=\"r\"><code>plot(cars)</code></pre>",
             "<p><img src=\"Full_test_suite_files/figure-html/Height_width_caption_dpi_out.height_out.width.png\" title=\"Test: Height, width, caption, dpi, out.height, out.width\" alt=\"Test: Height, width, caption, dpi, out.height, out.width\" width=\"288\" height=\"288\" /></p>",

             "</div>",
             "<div id=\"formula-tests\" class=\"section level1\">",
             "<h1 style=\"margin: 24pt 0pt 0pt 0pt;\">Formula tests</h1>",
             "<p><br /><span class=\"math\"><em>y</em> = <em>X</em><em>ß</em></span><br /></p>",
             "<p><br /><span class=\"math\"><U+2211><sub><em>n</em></sub><sup><em>i</em> = 1</sup><em>x</em><sub><em>i</em></sub> + 1</span><br /></p>",
             "<p><br /><span class=\"math\">$$\\frac{a}{(\\sum_{n}^{i=1}{x_i+1})+k}$$</span><br /></p>",
             "</div>", "<div id=\"highlighting-of-code\" class=\"section level1\">",
             "<h1 style=\"margin: 24pt 0pt 0pt 0pt;\">Highlighting of code</h1>",
             "<pre class=\"r\"><code>a &lt;- &quot;Some text&quot;", "b &lt;- 2",
             "c &lt;- b + 1234", "d &lt;- function(x){", "  print(x)", "}</code></pre>",
             "</div>", "", "", "", "", "</body>", "</html>")

fn <- "./tests/testthat/Full_test_suite.Rmd"
rmarkdown::render(fn, output_file = "./tmp.html")
tmp <- XML::xmlParse("./tests/testthat/tmp.html")
file.remove("./tests/testthat/tmp.html")
unlink("./tests/testthat/tmp_files", recursive = TRUE)

# An image without the caption element is one line with one
no_captions <- grep("<p><img [^>]+></p>$", out_str)
if (length(no_captions) > 0){
  core_str <- gsub("<p><img ([^>]+)></p>$", "\\1", out_str[no_captions])
  m <- strsplit(core_str, "\\b([^ =]+)=")
  m <- gregexpr("((?P<title>\\btitle=\"[^\"]+\")|(?P<src>\\bsrc=))", core_str, perl = TRUE)
  m[[1]][2]
  regmatches(core_str, m)
}